### ISSUE TITLE
Character Encoding in den Mails auf deutsch ist Kaputt

### ISSUE THREAD

**Issue by Tak0r** [tropicfruit/enlightened-approval-microsite#1]
Servus,

iso-8859-1 hat einfach keine Umlaute, iso-8859-15 geht meistens solange keine Sonderzeichen verwendet werden. Die beste Lösung wäre einfach auf UTF-8 umzustellen. Da eh eine HTML Mail gesendet wird, dürfte das auch so ziemlich jeder Mail Client verstehen der nicht aus den 80ern ist.

gruß aus der RheinMain Com

**Comment by smeagol91** [comment]
Last merge-commit changed the character encoding to UTF-8.
